In [ ]:
%pip install torch torchvision torchaudio

In [116]:
import torch
import torch.nn as nn
import torch.nn.functional as F

batch_size = 2
in_channels = 1
height, width = 5, 5
images = torch.randn(batch_size, in_channels, height, width)
print("Images input")
print(images.shape)
print(images)


Images input
torch.Size([2, 1, 5, 5])
tensor([[[[-1.4810, -0.4897, -1.8688, -0.8012,  1.3305],
          [ 0.8573,  0.5150, -0.0738, -1.3466,  1.1518],
          [ 0.2045, -0.7090,  0.4457, -1.2756, -0.7034],
          [-0.3336, -0.4023,  2.3146,  0.1836, -0.8412],
          [ 0.9116,  1.2257, -1.0256, -0.3944, -0.5429]]],


        [[[ 0.5863, -0.1345, -0.3005,  0.0024, -0.3322],
          [-0.2621,  0.9806,  0.1233, -0.8503, -0.3742],
          [ 1.2416, -1.0087, -0.1818, -0.3855,  0.9696],
          [-0.7441, -0.4278,  0.1171,  1.1782, -1.6178],
          [-0.7069, -0.5989, -0.0132,  0.7005,  0.7016]]]])


In [121]:
kernel_size = 3
stride = 1
padding = 0
im2col_result = F.unfold(images, kernel_size=kernel_size, stride=stride, padding=padding)
print("im2col result")
print(im2col_result.shape)
print(im2col_result)


im2col result
torch.Size([2, 9, 9])
tensor([[[-1.4810, -0.4897, -1.8688,  0.8573,  0.5150, -0.0738,  0.2045,
          -0.7090,  0.4457],
         [-0.4897, -1.8688, -0.8012,  0.5150, -0.0738, -1.3466, -0.7090,
           0.4457, -1.2756],
         [-1.8688, -0.8012,  1.3305, -0.0738, -1.3466,  1.1518,  0.4457,
          -1.2756, -0.7034],
         [ 0.8573,  0.5150, -0.0738,  0.2045, -0.7090,  0.4457, -0.3336,
          -0.4023,  2.3146],
         [ 0.5150, -0.0738, -1.3466, -0.7090,  0.4457, -1.2756, -0.4023,
           2.3146,  0.1836],
         [-0.0738, -1.3466,  1.1518,  0.4457, -1.2756, -0.7034,  2.3146,
           0.1836, -0.8412],
         [ 0.2045, -0.7090,  0.4457, -0.3336, -0.4023,  2.3146,  0.9116,
           1.2257, -1.0256],
         [-0.7090,  0.4457, -1.2756, -0.4023,  2.3146,  0.1836,  1.2257,
          -1.0256, -0.3944],
         [ 0.4457, -1.2756, -0.7034,  2.3146,  0.1836, -0.8412, -1.0256,
          -0.3944, -0.5429]],

        [[ 0.5863, -0.1345, -0.3005, -0.2621

In [124]:
out_channels = 4
conv_kernel = torch.randn(out_channels, in_channels, kernel_size, kernel_size)
kernel_matrix = conv_kernel.view(out_channels, -1)
print("Kernels Flattened")
print(kernel_matrix.shape)
print(kernel_matrix)


Kernels Flattened
torch.Size([4, 9])
tensor([[-0.5057,  0.3242, -0.9349, -2.7210,  0.4371, -2.2433, -0.5837, -1.0012,
         -0.1248],
        [ 0.8013, -0.6438, -0.2755, -0.3278,  0.1188,  0.7968,  0.6063,  1.2937,
          1.3797],
        [ 0.1598,  0.3949,  1.2515,  0.4712, -1.0708,  0.4329, -0.5294,  0.3866,
         -1.2594],
        [ 0.4063, -1.6015, -1.7729, -2.5825,  3.4356,  1.2719,  1.8954,  0.1855,
         -0.0976]])


In [128]:
im2col_conv2d_result = torch.matmul(kernel_matrix, im2col_result)
print("Convolution using im2col (Unfold)")
print(im2col_conv2d_result.shape)
print(im2col_conv2d_result)


Convolution using im2col (Unfold)
torch.Size([2, 4, 9])
tensor([[[  0.9300,   2.1048,  -2.4255,  -1.7551,   3.8547,  -3.0984,  -6.8418,
            3.7506,  -3.2507],
         [ -0.8135,  -1.8323,  -2.9167,   3.0502,   3.1038,   0.1128,   3.1267,
           -1.0784,  -1.9162],
         [ -3.8917,   0.0741,   3.1126,  -1.5974,  -2.1191,   2.0743,   2.8688,
           -4.6708,   0.2914],
         [  3.1699,  -0.2183,  -4.1291,  -3.6754,   4.1035,  -1.8403,   4.9070,
           12.6554,  -4.9095]],

        [[  1.1141,   0.0807,   0.9668,  -2.2282,   3.8544,  -2.8831,   1.8041,
           -0.3410,   2.1049],
         [  0.1368,  -2.2779,   0.1383,  -2.3899,   2.4601,   0.8989,   0.7590,
            1.0941,   0.5142],
         [ -2.2740,   0.7740,  -0.9300,   2.1671,  -2.5184,   2.3932,  -0.1100,
           -1.1025,  -1.4804],
         [  7.3730,  -4.6759,  -3.7635, -10.2997,   2.2944,   3.0523,   1.5935,
            2.3644,   0.5488]]])


In [131]:
out_height = (height - kernel_size) // stride + 1
out_width = (width - kernel_size) // stride + 1
output_feature_map = im2col_conv2d_result.view(batch_size, out_channels, out_height, out_width)
print("Reshape im2col multiplication result into output feature map")
print(output_feature_map.shape)
print(output_feature_map)


Reshape im2col multiplication result into output feature map
torch.Size([2, 4, 3, 3])
tensor([[[[  0.9300,   2.1048,  -2.4255],
          [ -1.7551,   3.8547,  -3.0984],
          [ -6.8418,   3.7506,  -3.2507]],

         [[ -0.8135,  -1.8323,  -2.9167],
          [  3.0502,   3.1038,   0.1128],
          [  3.1267,  -1.0784,  -1.9162]],

         [[ -3.8917,   0.0741,   3.1126],
          [ -1.5974,  -2.1191,   2.0743],
          [  2.8688,  -4.6708,   0.2914]],

         [[  3.1699,  -0.2183,  -4.1291],
          [ -3.6754,   4.1035,  -1.8403],
          [  4.9070,  12.6554,  -4.9095]]],


        [[[  1.1141,   0.0807,   0.9668],
          [ -2.2282,   3.8544,  -2.8831],
          [  1.8041,  -0.3410,   2.1049]],

         [[  0.1368,  -2.2779,   0.1383],
          [ -2.3899,   2.4601,   0.8989],
          [  0.7590,   1.0941,   0.5142]],

         [[ -2.2740,   0.7740,  -0.9300],
          [  2.1671,  -2.5184,   2.3932],
          [ -0.1100,  -1.1025,  -1.4804]],

         [[  7.3

In [ ]:
conv_layer = torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=stride, padding=padding, bias=False)
conv_layer.weight.data = conv_kernel

conv2d_result = conv_layer(images)
conv2d_no_grad = conv2d_result.detach()
print("Convolution2d call result")
print(conv2d_no_grad.shape)
print(conv2d_no_grad)


Convolution2d call result
torch.Size([2, 4, 3, 3])
tensor([[[[  0.9300,   2.1048,  -2.4255],
          [ -1.7551,   3.8547,  -3.0984],
          [ -6.8418,   3.7506,  -3.2507]],

         [[ -0.8135,  -1.8323,  -2.9167],
          [  3.0502,   3.1038,   0.1128],
          [  3.1267,  -1.0784,  -1.9162]],

         [[ -3.8917,   0.0741,   3.1126],
          [ -1.5974,  -2.1191,   2.0743],
          [  2.8688,  -4.6708,   0.2914]],

         [[  3.1699,  -0.2183,  -4.1291],
          [ -3.6754,   4.1035,  -1.8403],
          [  4.9070,  12.6554,  -4.9095]]],


        [[[  1.1141,   0.0807,   0.9668],
          [ -2.2282,   3.8544,  -2.8831],
          [  1.8041,  -0.3410,   2.1049]],

         [[  0.1368,  -2.2779,   0.1383],
          [ -2.3899,   2.4601,   0.8989],
          [  0.7590,   1.0941,   0.5142]],

         [[ -2.2740,   0.7740,  -0.9300],
          [  2.1671,  -2.5184,   2.3932],
          [ -0.1100,  -1.1025,  -1.4804]],

         [[  7.3730,  -4.6759,  -3.7635],
         

In [ ]:
errors = conv2d_no_grad - output_feature_map
print(errors)

tensor([[[[ 1.7881e-07,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  2.3842e-07],
          [ 0.0000e+00,  0.0000e+00, -4.7684e-07]],

         [[ 0.0000e+00,  1.1921e-07,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  7.4506e-08],
          [ 0.0000e+00, -1.1921e-07, -1.1921e-07]],

         [[ 0.0000e+00,  9.6858e-08,  2.3842e-07],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00, -4.7684e-07, -2.9802e-08]],

         [[ 0.0000e+00, -2.6822e-07, -4.7684e-07],
          [ 0.0000e+00,  0.0000e+00, -5.9605e-07],
          [ 0.0000e+00, -9.5367e-07, -4.7684e-07]]],


        [[[-1.1921e-07, -7.4506e-09, -1.1921e-07],
          [ 0.0000e+00,  4.7684e-07,  2.3842e-07],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 5.9605e-08,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00, -2.3842e-07, -1.1921e-07],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00, -5.9605e-08, -5.9605e-08],
          [ 0.000