In [ ]:
%pip install torch torchvision torchaudio

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

batch_size = 2
in_channels = 1
height, width = 6,6
images = torch.rand(batch_size, in_channels, height, width)
print("Images input")
print(images.shape)
print(images)


Images input
torch.Size([2, 1, 6, 6])
tensor([[[[0.5463, 0.7340, 0.0529, 0.3832, 0.0270, 0.0762],
          [0.8616, 0.4619, 0.0695, 0.2323, 0.3086, 0.1032],
          [0.4636, 0.2489, 0.1030, 0.5925, 0.8976, 0.3730],
          [0.1945, 0.5421, 0.6404, 0.4513, 0.6649, 0.8863],
          [0.7978, 0.1297, 0.7143, 0.4763, 0.7851, 0.6691],
          [0.2878, 0.9141, 0.4255, 0.4009, 0.6997, 0.7527]]],


        [[[0.6216, 0.5607, 0.9803, 0.7456, 0.4444, 0.6561],
          [0.1483, 0.4778, 0.0693, 0.7137, 0.3872, 0.3660],
          [0.8805, 0.1232, 0.2228, 0.4856, 0.0156, 0.6362],
          [0.8774, 0.1551, 0.5922, 0.4736, 0.5383, 0.8704],
          [0.8192, 0.9175, 0.8558, 0.5901, 0.9186, 0.8109],
          [0.0681, 0.9770, 0.4072, 0.3955, 0.9965, 0.8976]]]])


In [26]:
kernel_size = 3
stride = 1
padding = 0
im2col_result = F.unfold(images, kernel_size=kernel_size, stride=stride, padding=padding)
print("im2col result")
print(im2col_result.shape)
print(im2col_result)


im2col result
torch.Size([2, 9, 16])
tensor([[[0.5463, 0.7340, 0.0529, 0.3832, 0.8616, 0.4619, 0.0695, 0.2323,
          0.4636, 0.2489, 0.1030, 0.5925, 0.1945, 0.5421, 0.6404, 0.4513],
         [0.7340, 0.0529, 0.3832, 0.0270, 0.4619, 0.0695, 0.2323, 0.3086,
          0.2489, 0.1030, 0.5925, 0.8976, 0.5421, 0.6404, 0.4513, 0.6649],
         [0.0529, 0.3832, 0.0270, 0.0762, 0.0695, 0.2323, 0.3086, 0.1032,
          0.1030, 0.5925, 0.8976, 0.3730, 0.6404, 0.4513, 0.6649, 0.8863],
         [0.8616, 0.4619, 0.0695, 0.2323, 0.4636, 0.2489, 0.1030, 0.5925,
          0.1945, 0.5421, 0.6404, 0.4513, 0.7978, 0.1297, 0.7143, 0.4763],
         [0.4619, 0.0695, 0.2323, 0.3086, 0.2489, 0.1030, 0.5925, 0.8976,
          0.5421, 0.6404, 0.4513, 0.6649, 0.1297, 0.7143, 0.4763, 0.7851],
         [0.0695, 0.2323, 0.3086, 0.1032, 0.1030, 0.5925, 0.8976, 0.3730,
          0.6404, 0.4513, 0.6649, 0.8863, 0.7143, 0.4763, 0.7851, 0.6691],
         [0.4636, 0.2489, 0.1030, 0.5925, 0.1945, 0.5421, 0.6404, 0.4

In [12]:
out_channels = 4
conv_kernel = torch.randn(out_channels, in_channels, kernel_size, kernel_size)
kernel_matrix = conv_kernel.view(out_channels, -1)
print("Kernels Flattened")
print(kernel_matrix.shape)
print(kernel_matrix)


Kernels Flattened
torch.Size([4, 9])
tensor([[ 0.0903,  1.6831, -1.2517,  1.4519, -0.4311, -1.9387, -0.5444,  0.6553,
         -0.7051],
        [ 0.2976,  0.4306,  2.2662,  1.4804, -0.6277, -0.7304,  0.8510,  1.0613,
         -0.4742],
        [ 0.3410,  2.0507, -1.1369, -0.2150,  0.6438,  1.4654, -0.1203, -0.1643,
          0.8366],
        [ 0.3783, -1.2285, -0.2971,  1.1674,  0.0966,  1.3630, -0.2323,  1.2406,
          2.0313]])


In [28]:
im2col_conv2d_result = torch.matmul(kernel_matrix, im2col_result)
print("Convolution using im2col (Unfold)")
print(im2col_conv2d_result.shape)
print(im2col_conv2d_result)


Convolution using im2col (Unfold)
torch.Size([2, 4, 16])
tensor([[[ 1.9738, -0.6198, -0.2823, -0.0087,  0.9321, -1.1576, -2.3568,
          -0.2736, -1.7140, -0.8481, -1.3011, -0.4691, -0.0118, -0.9827,
          -1.1674, -1.1842],
         [ 2.1431,  1.6201,  0.2644,  1.6531,  1.5048,  1.4917,  0.6536,
           1.1467,  0.4364,  2.1749,  3.2402,  1.9328,  3.3337,  1.8950,
           2.5326,  2.8796],
         [ 1.8347,  0.6577,  2.0010,  0.4927,  1.7967,  1.1241,  2.2288,
           2.1696,  2.2772,  0.8449,  1.8495,  3.6219,  1.5799,  2.2705,
           2.1596,  2.3598],
         [ 0.8447,  2.2349,  2.5997,  2.2643,  2.3717,  2.7137,  2.8119,
           3.4853,  2.4180,  2.9250,  2.7615,  3.0323,  3.0663,  1.2839,
           3.2601,  2.9384]],

        [[-0.9080, -0.2159,  0.0155, -0.5491,  0.7306, -1.6226,  0.4152,
          -0.7958, -0.3812, -1.5248, -0.2970, -2.2492, -0.9501, -0.3069,
          -1.2811, -1.4474],
         [ 3.2915,  2.5324,  1.6893,  2.5744,  2.1009,  2.0130,  1

In [29]:
out_height = (height - kernel_size) // stride + 1
out_width = (width - kernel_size) // stride + 1
output_feature_map = im2col_conv2d_result.view(batch_size, out_channels, out_height, out_width)
print("Reshape im2col multiplication result into output feature map")
print(output_feature_map.shape)
print(output_feature_map)


Reshape im2col multiplication result into output feature map
torch.Size([2, 4, 4, 4])
tensor([[[[ 1.9738, -0.6198, -0.2823, -0.0087],
          [ 0.9321, -1.1576, -2.3568, -0.2736],
          [-1.7140, -0.8481, -1.3011, -0.4691],
          [-0.0118, -0.9827, -1.1674, -1.1842]],

         [[ 2.1431,  1.6201,  0.2644,  1.6531],
          [ 1.5048,  1.4917,  0.6536,  1.1467],
          [ 0.4364,  2.1749,  3.2402,  1.9328],
          [ 3.3337,  1.8950,  2.5326,  2.8796]],

         [[ 1.8347,  0.6577,  2.0010,  0.4927],
          [ 1.7967,  1.1241,  2.2288,  2.1696],
          [ 2.2772,  0.8449,  1.8495,  3.6219],
          [ 1.5799,  2.2705,  2.1596,  2.3598]],

         [[ 0.8447,  2.2349,  2.5997,  2.2643],
          [ 2.3717,  2.7137,  2.8119,  3.4853],
          [ 2.4180,  2.9250,  2.7615,  3.0323],
          [ 3.0663,  1.2839,  3.2601,  2.9384]]],


        [[[-0.9080, -0.2159,  0.0155, -0.5491],
          [ 0.7306, -1.6226,  0.4152, -0.7958],
          [-0.3812, -1.5248, -0.2970, -2

In [30]:
conv_layer = torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=stride, padding=padding, bias=False)
conv_layer.weight.data = conv_kernel

conv2d_result = conv_layer(images)
conv2d_no_grad = conv2d_result.detach()
print("Convolution2d call result")
print(conv2d_no_grad.shape)
print(conv2d_no_grad)


Convolution2d call result
torch.Size([2, 4, 4, 4])
tensor([[[[ 1.9738, -0.6198, -0.2823, -0.0087],
          [ 0.9321, -1.1576, -2.3568, -0.2736],
          [-1.7140, -0.8481, -1.3011, -0.4691],
          [-0.0118, -0.9827, -1.1674, -1.1842]],

         [[ 2.1431,  1.6201,  0.2644,  1.6531],
          [ 1.5048,  1.4917,  0.6536,  1.1467],
          [ 0.4364,  2.1749,  3.2402,  1.9328],
          [ 3.3337,  1.8950,  2.5326,  2.8796]],

         [[ 1.8347,  0.6577,  2.0010,  0.4927],
          [ 1.7967,  1.1241,  2.2288,  2.1696],
          [ 2.2772,  0.8449,  1.8495,  3.6219],
          [ 1.5799,  2.2705,  2.1596,  2.3598]],

         [[ 0.8447,  2.2349,  2.5997,  2.2643],
          [ 2.3717,  2.7137,  2.8119,  3.4853],
          [ 2.4180,  2.9250,  2.7615,  3.0323],
          [ 3.0663,  1.2839,  3.2601,  2.9384]]],


        [[[-0.9080, -0.2159,  0.0155, -0.5491],
          [ 0.7306, -1.6226,  0.4152, -0.7958],
          [-0.3812, -1.5248, -0.2970, -2.2492],
          [-0.9501, -0.3069

In [31]:
errors = conv2d_no_grad - output_feature_map
print(errors)

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])
