In [ ]:
%pip install torch torchvision torchaudio

In [190]:
import torch
import torch.nn as nn
import torch.nn.functional as F

batch_size = 2
in_channels = 3
height, width = 5, 5
images = torch.rand(batch_size, in_channels, height, width)
print("Images input")
print(images.shape)
print(images)


Images input
torch.Size([2, 3, 5, 5])
tensor([[[[0.7069, 0.0053, 0.7509, 0.4997, 0.5291],
          [0.2079, 0.6302, 0.7143, 0.2303, 0.2249],
          [0.7330, 0.0901, 0.9821, 0.1887, 0.7630],
          [0.5262, 0.5468, 0.3565, 0.8704, 0.2939],
          [0.3144, 0.7664, 0.2320, 0.2245, 0.4621]],

         [[0.0337, 0.6861, 0.5563, 0.3548, 0.2485],
          [0.4878, 0.4077, 0.5964, 0.5390, 0.3762],
          [0.1917, 0.0566, 0.5194, 0.4995, 0.9550],
          [0.5272, 0.1270, 0.3567, 0.5133, 0.5403],
          [0.8973, 0.9543, 0.2164, 0.9404, 0.6786]],

         [[0.8636, 0.6439, 0.9322, 0.9452, 0.7857],
          [0.2328, 0.1110, 0.8237, 0.1697, 0.7060],
          [0.4322, 0.1705, 0.4810, 0.9881, 0.9120],
          [0.1036, 0.3003, 0.1644, 0.2351, 0.4834],
          [0.0425, 0.0286, 0.8794, 0.7378, 0.5249]]],


        [[[0.2597, 0.1282, 0.0666, 0.6275, 0.5216],
          [0.2106, 0.2725, 0.9120, 0.8386, 0.8995],
          [0.0014, 0.6912, 0.8913, 0.3281, 0.9155],
          [0.5862,

In [192]:
kernel_size = 3
stride = 1
padding = 0
im2col_result = F.unfold(images, kernel_size=kernel_size, stride=stride, padding=padding)
print("im2col result")
print(im2col_result.shape)
print(im2col_result)


im2col result
torch.Size([2, 27, 9])
tensor([[[0.7069, 0.0053, 0.7509, 0.2079, 0.6302, 0.7143, 0.7330, 0.0901,
          0.9821],
         [0.0053, 0.7509, 0.4997, 0.6302, 0.7143, 0.2303, 0.0901, 0.9821,
          0.1887],
         [0.7509, 0.4997, 0.5291, 0.7143, 0.2303, 0.2249, 0.9821, 0.1887,
          0.7630],
         [0.2079, 0.6302, 0.7143, 0.7330, 0.0901, 0.9821, 0.5262, 0.5468,
          0.3565],
         [0.6302, 0.7143, 0.2303, 0.0901, 0.9821, 0.1887, 0.5468, 0.3565,
          0.8704],
         [0.7143, 0.2303, 0.2249, 0.9821, 0.1887, 0.7630, 0.3565, 0.8704,
          0.2939],
         [0.7330, 0.0901, 0.9821, 0.5262, 0.5468, 0.3565, 0.3144, 0.7664,
          0.2320],
         [0.0901, 0.9821, 0.1887, 0.5468, 0.3565, 0.8704, 0.7664, 0.2320,
          0.2245],
         [0.9821, 0.1887, 0.7630, 0.3565, 0.8704, 0.2939, 0.2320, 0.2245,
          0.4621],
         [0.0337, 0.6861, 0.5563, 0.4878, 0.4077, 0.5964, 0.1917, 0.0566,
          0.5194],
         [0.6861, 0.5563, 0.3548,

In [195]:
out_channels = 4
conv_kernel = torch.randn(out_channels, in_channels, kernel_size, kernel_size)
kernel_matrix = conv_kernel.view(out_channels, -1)
print("Kernels Flattened")
print(kernel_matrix.shape)
print(kernel_matrix)


Kernels Flattened
torch.Size([4, 27])
tensor([[ 0.1130,  0.2786, -2.5931,  0.6310,  0.5631,  0.1642,  1.1291,  0.5065,
          1.0089, -0.8507, -0.6818,  1.1087, -0.2064,  0.9678, -1.0432, -0.7228,
         -0.3849,  0.8567, -0.0239, -2.2368, -0.4590, -0.6735, -0.5429, -0.2044,
          0.6070, -1.3749,  0.4336],
        [ 1.1086,  0.7661,  1.2196, -0.7907,  1.8599,  0.1903,  0.3106, -1.4957,
         -0.2568, -0.4976, -0.4762, -1.3379, -0.2921, -2.0327, -0.9010,  0.8681,
         -0.4442,  0.3199,  0.2060, -0.1856, -0.3679,  0.5271,  2.1218,  0.5435,
         -0.9063,  0.0530, -0.5440],
        [-0.5705,  1.6427,  0.9978, -0.0596,  0.9667,  1.3434,  0.9802,  1.6528,
          3.4600, -0.4798, -0.4949, -0.7036,  0.1509, -0.2200, -0.2494, -0.1637,
         -0.6708,  0.6386,  0.9242,  0.1405,  0.6504,  1.0816,  0.5065,  0.4881,
          1.7232,  0.1357,  0.7624],
        [ 1.0595, -0.5264, -0.2021, -0.6636, -2.1159, -0.5839,  1.5604, -0.4817,
          0.1493, -0.6285, -1.7894,  0.93

In [199]:
im2col_conv2d_result = torch.matmul(kernel_matrix, im2col_result)
print("Convolution using im2col (Unfold)")
print(im2col_conv2d_result.shape)
print(im2col_conv2d_result)


Convolution using im2col (Unfold)
torch.Size([2, 4, 9])
tensor([[[-1.3594, -3.1307, -2.6988, -1.8231, -0.4281, -1.3014, -2.0887,
          -1.0848, -3.2412],
         [ 0.2759, -1.5006, -0.2329, -0.3372,  1.1805, -0.8094,  0.6596,
           0.0132, -0.8621],
         [ 8.8664,  7.0324,  9.2522,  6.6327,  7.3034,  6.3978,  4.7200,
           6.7408,  6.0534],
         [ 2.8690,  0.6862,  4.2091,  2.8104,  0.4525,  5.8369,  2.3857,
           3.3272,  0.0399]],

        [[-1.1200, -2.0495, -0.6395, -2.7252, -2.4670, -1.8133,  0.0256,
          -0.5203, -2.4184],
         [-1.8990, -0.3966, -1.6623, -1.4541,  0.2251, -1.7042,  0.0368,
          -0.5294,  0.0919],
         [ 7.5624,  7.3886, 10.3410,  7.2086,  8.1734,  9.9842,  9.9393,
           8.0781,  8.6809],
         [ 3.7013,  2.3020,  1.1976,  3.4223,  1.3736,  0.7871,  0.8416,
           2.5975,  4.8731]]])


In [203]:
out_height = (height - kernel_size) // stride + 1
out_width = (width - kernel_size) // stride + 1
output_feature_map = im2col_conv2d_result.view(batch_size, out_channels, out_height, out_width)
print("Reshape im2col multiplication result into output feature map")
print(output_feature_map.shape)
print(output_feature_map)


Reshape im2col multiplication result into output feature map
torch.Size([2, 4, 3, 3])
tensor([[[[-1.3594, -3.1307, -2.6988],
          [-1.8231, -0.4281, -1.3014],
          [-2.0887, -1.0848, -3.2412]],

         [[ 0.2759, -1.5006, -0.2329],
          [-0.3372,  1.1805, -0.8094],
          [ 0.6596,  0.0132, -0.8621]],

         [[ 8.8664,  7.0324,  9.2522],
          [ 6.6327,  7.3034,  6.3978],
          [ 4.7200,  6.7408,  6.0534]],

         [[ 2.8690,  0.6862,  4.2091],
          [ 2.8104,  0.4525,  5.8369],
          [ 2.3857,  3.3272,  0.0399]]],


        [[[-1.1200, -2.0495, -0.6395],
          [-2.7252, -2.4670, -1.8133],
          [ 0.0256, -0.5203, -2.4184]],

         [[-1.8990, -0.3966, -1.6623],
          [-1.4541,  0.2251, -1.7042],
          [ 0.0368, -0.5294,  0.0919]],

         [[ 7.5624,  7.3886, 10.3410],
          [ 7.2086,  8.1734,  9.9842],
          [ 9.9393,  8.0781,  8.6809]],

         [[ 3.7013,  2.3020,  1.1976],
          [ 3.4223,  1.3736,  0.7871],
 

In [213]:
conv_layer = torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=stride, padding=padding, bias=False)
conv_layer.weight.data = conv_kernel

conv2d_result = conv_layer(images)
conv2d_no_grad = conv2d_result.detach()
print("Convolution2d call result")
print(conv2d_no_grad.shape)
print(conv2d_no_grad)


Convolution2d call result
torch.Size([2, 4, 3, 3])
tensor([[[[-1.3594, -3.1307, -2.6988],
          [-1.8231, -0.4281, -1.3014],
          [-2.0887, -1.0848, -3.2412]],

         [[ 0.2759, -1.5006, -0.2329],
          [-0.3372,  1.1805, -0.8094],
          [ 0.6596,  0.0132, -0.8621]],

         [[ 8.8664,  7.0324,  9.2522],
          [ 6.6327,  7.3034,  6.3978],
          [ 4.7200,  6.7408,  6.0534]],

         [[ 2.8690,  0.6862,  4.2091],
          [ 2.8104,  0.4525,  5.8369],
          [ 2.3857,  3.3272,  0.0399]]],


        [[[-1.1200, -2.0495, -0.6395],
          [-2.7252, -2.4670, -1.8133],
          [ 0.0256, -0.5203, -2.4184]],

         [[-1.8990, -0.3966, -1.6623],
          [-1.4541,  0.2251, -1.7042],
          [ 0.0368, -0.5294,  0.0919]],

         [[ 7.5624,  7.3886, 10.3410],
          [ 7.2086,  8.1734,  9.9842],
          [ 9.9393,  8.0781,  8.6809]],

         [[ 3.7013,  2.3020,  1.1976],
          [ 3.4223,  1.3736,  0.7871],
          [ 0.8416,  2.5975,  4.8731

In [211]:
errors = conv2d_no_grad - output_feature_map
print(errors)

tensor([[[[-1.1921e-07, -2.3842e-07, -4.7684e-07],
          [ 0.0000e+00, -5.9605e-08,  2.3842e-07],
          [-2.3842e-07, -1.1921e-07, -7.1526e-07]],

         [[ 2.9802e-07, -4.7684e-07,  2.9802e-08],
          [ 2.9802e-08,  1.1921e-07,  3.5763e-07],
          [ 2.3842e-07,  5.9605e-08, -2.9802e-07]],

         [[ 0.0000e+00, -4.7684e-07, -9.5367e-07],
          [-9.5367e-07,  4.7684e-07,  4.7684e-07],
          [ 0.0000e+00,  4.7684e-07,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  2.9802e-07,  0.0000e+00],
          [ 0.0000e+00, -4.7684e-07,  1.4901e-08]]],


        [[[-2.3842e-07, -2.3842e-07, -2.3842e-07],
          [ 0.0000e+00,  1.1921e-06,  1.1921e-07],
          [ 2.5332e-07, -1.7881e-07,  7.1526e-07]],

         [[ 4.7684e-07,  8.9407e-08,  0.0000e+00],
          [ 1.1921e-07, -2.3842e-07, -2.3842e-07],
          [ 2.8312e-07,  1.7881e-07,  5.9605e-08]],

         [[ 4.7684e-07, -4.7684e-07,  0.0000e+00],
          [ 9.536